SELECT AL1.AWB_NBR, AL2.TRACKING_NBR FROM MISA_PROD_VIEW_DB.AIRBILL_DIM AL1, MISA_PROD_VIEW_DB.CARRIER_PIECE_FACT AL2 WHERE (AL1.PM_PRIMARYKEY=AL2.AIRBILL_WNBR)  AND (

{awbs}

) AND AL2.PM_CURRENT_FLAG=1
