SELECT DISTINCT 
AL3.AWB_NBR, 
AL4.EMPLOYEE_NBR, 
AL8.ENTRY_CATEGORY_TYPE_CD, 
min(AL1.ACTIVITY_TMSTP),
COUNT (DISTINCT AL1.ACTIVITY_DATA_DESC) as ACTIVITY_COUNT, 
count(distinct Case when AL7.INTERCEPT_CD in ('AEC', 'ATF', 'AGI', 'CIT', 'DIP', 'HCA', 'KPC', 'PSN', 'NRC', 'SMN', 'TCA') then 1 end) as TRUE_OGD,
-- AL7.INTERCEPT_CD,
max(case when AL1.ACTIVITY_DATA_DESC like ('REVIEW PERFORMED FOR AGENCY%') then 1 end) AS ACTIVITY_LIKE_REVIEW_PERFORMED_FOR_AGENCY, 
count( distinct case when AL1.ACTIVITY_DATA_DESC like ('SHIPMENT UPDATE') then 1 end) AS ACTIVITY_LIKE_SHIPMENT_UPDATE, 
count( case when AL1.ACTIVITY_DATA_DESC like ('ENTRY TYPE%') then 1 end) AS COUNT_ACTIVITY_LIKE_ENTRY_TYPE,
count( case when AL1.ACTIVITY_DATA_DESC like ('BROKER CD%') then 1 end) AS COUNT_ACTIVITY_LIKE_BROKER_CD, 
count( distinct case when AL1.ACTIVITY_DATA_DESC like ('% SHIPMENT INTERCEPT %') then 1 end) AS ACTIVITY_LIKE_SHIPMENT_INTERCEPT, 
count( distinct case when AL1.ACTIVITY_DATA_DESC like ('%PIECE INTERCEPT%') then 1 end)AS ACTIVITY_LIKE_PIECE_INTERCEPT, 
AL5.CUSTOMS_VALUE_AMT 
FROM 
MISA_PROD_VIEW_DB.TIME_DIM AL2, 
MISA_PROD_VIEW_DB.AIRBILL_DIM AL3, 
MISA_PROD_VIEW_DB.EMPLOYEE_DIM AL4, 
MISA_PROD_VIEW_DB.CCII_CLEARANCE_ACTIVITY_FACT AL1 
LEFT OUTER JOIN MISA_PROD_VIEW_DB.CCII_SHIPMENT_CORE_CLRNC_FACT AL8 ON (AL1.AIRBILL_WNBR=AL8.AIRBILL_WNBR) , 
MISA_PROD_VIEW_DB.CARRIER_SHIPMENT_FACT AL5 
LEFT OUTER JOIN MISA_PROD_VIEW_DB.CCII_INTERCEPT_FACT AL6 ON (AL6.AIRBILL_WNBR=AL5.AIRBILL_WNBR) 
LEFT OUTER JOIN MISA_PROD_VIEW_DB.CCII_INTERCEPT_CODE_DIM AL7 ON (AL6.INTERCEPT_CODE_WNBR=AL7.PM_PRIMARYKEY) 
WHERE 
AL1.AIRBILL_WNBR <> 0 AND 
AL5.AIRBILL_WNBR <> 0 AND 
AL6.AIRBILL_WNBR <> 0 AND
AL8.AIRBILL_WNBR <> 0 AND
(AL4.PM_PRIMARYKEY=AL1.CREATED_EMPL_WNBR AND 
AL3.PM_PRIMARYKEY=AL5.AIRBILL_WNBR AND 
AL5.AIRBILL_WNBR=AL1.AIRBILL_WNBR AND 
AL2.TIME_WNBR=AL1.ACTIVITY_DT_WNBR)  AND
-- MODIFY HERE TO HARDCODE EMPLOYEES
-- AL4.EMPLOYEE_NBR IN ( 

-- '2527987'
-- ) AND

-- CHANGE DATE

(AL2.DATE_DT BETWEEN

DATE {start_date} AND DATE {end_date}

) AND

-- CHANGE DATE

AL1.PM_CURRENT_FLAG=1 AND 
AL5.PM_CURRENT_FLAG=1 AND 
AL6.PM_CURRENT_FLAG=1 AND 
AL8.PM_CURRENT_FLAG=1 AND
AL8.ENTRY_CATEGORY_TYPE_CD IN ('HVS', 'LVS', 'OIC')
-- )) 
GROUP BY 
AL3.AWB_NBR,
-- AL7.INTERCEPT_CD,
AL4.EMPLOYEE_NBR, 
AL8.ENTRY_CATEGORY_TYPE_CD, 
AL5.CUSTOMS_VALUE_AMT 
HAVING max(case when AL1.ACTIVITY_DATA_DESC like ('REVIEW PERFORMED FOR AGENCY%') then 1 end)=1 
ORDER BY  2,  4;

-- NEW QUERY.


-- --SELECT MISA_PROD_VIEW_DB.EMPLOYEE_DIM.PM_PRIMARYKEY WHERE
-- --
-- --MISA_PROD_VIEW_DB.EMPLOYEE_DIM.EMPLOYEE_NBR = '2527987';


-- SELECT * FROM MISA_PROD_VIEW_DB.CCII_CLEARANCE_ACTIVITY_FACT WHERE MISA_PROD_VIEW_DB.CCII_CLEARANCE_ACTIVITY_FACT.CREATED_EMPL_WNBR = 

-- '1069900000';
-- --'458893600';

-- --PM FOR 5112357: 458893600
-- --PM FOR 2527987: 1069900000