WITH clr AS (
	SELECT ACTIVITY_DATA_DESC, CREATED_EMPL_WNBR, AIRBILL_WNBR, ACTIVITY_TMSTP
	FROM MISA_PROD_VIEW_DB.CCII_CLEARANCE_ACTIVITY_FACT
	WHERE AIRBILL_WNBR <> 0 AND AIRBILL_WNBR IS NOT NULL AND PM_CURRENT_FLAG=1
	AND ACTIVITY_TMSTP BETWEEN DATE {start_date} AND DATE {end_date} --Change dates to use here
),
airbill AS (
	SELECT PM_PRIMARYKEY, AWB_NBR
	FROM MISA_PROD_VIEW_DB.AIRBILL_DIM
	WHERE PM_PRIMARYKEY <> 0 AND PM_PRIMARYKEY IS NOT NULL AND PM_CURRENT_FLAG=1
),
emp AS (
	SELECT emp_dim.EMPLOYEE_NBR, emp_dim.PM_PRIMARYKEY
	FROM MISA_PROD_VIEW_DB.EMPLOYEE_DIM emp_dim
	WHERE PM_PRIMARYKEY <> 0 AND PM_PRIMARYKEY IS NOT NULL AND PM_CURRENT_FLAG=1
),
emp_info AS (
	SELECT emp_nbr
	FROM UI_ISH_PROD_DB.employee
	WHERE job_cd = 'NC97C' --This is the job code for GTS Clearance Select Reps
),
shp_fct AS (
	SELECT CUSTOMS_VALUE_AMT, AIRBILL_WNBR
	FROM MISA_PROD_VIEW_DB.CARRIER_SHIPMENT_FACT
	WHERE AIRBILL_WNBR <> 0 AND AIRBILL_WNBR IS NOT NULL AND PM_CURRENT_FLAG=1
),
int_fct AS (
	SELECT AIRBILL_WNBR, INTERCEPT_CODE_WNBR
	FROM MISA_PROD_VIEW_DB.CCII_INTERCEPT_FACT
	WHERE AIRBILL_WNBR <> 0 AND AIRBILL_WNBR IS NOT NULL AND PM_CURRENT_FLAG=1
),
int_code_dim AS (
	SELECT PM_PRIMARYKEY, INTERCEPT_CD
	FROM MISA_PROD_VIEW_DB.CCII_INTERCEPT_CODE_DIM
	WHERE PM_PRIMARYKEY <> 0 AND PM_PRIMARYKEY IS NOT NULL AND PM_CURRENT_FLAG=1
	AND INTERCEPT_CD IN --Specify intercept codes to track below
	('AEC', 'ATF', 'AGI', 'CIT', 'DIP', 'HCA', 'KPC', 'PSN', 'NRC', 'SMN', 'TCA', --General
	'CSA', 'DES', 'DESC', 'ILG', 'OXC', 'VAL', 'WGT', 'VER', 'REF', 'QST' --Warnings / Further action
	'FRD', 'PRO', --Critical
	'ADP', 'ADE', 'C20', 'XMT', 'H', 'IPD', 'MMM', 'S', 'SS', 'I', 'II', 'NWD', 'ODA', --Port / Brand specific
	'HVC', 'TPL')
),
shp_core_clr_fct AS (
	SELECT AIRBILL_WNBR, ENTRY_CATEGORY_TYPE_CD
	FROM MISA_PROD_VIEW_DB.CCII_SHIPMENT_CORE_CLRNC_FACT
	WHERE AIRBILL_WNBR <> 0 AND AIRBILL_WNBR IS NOT NULL AND PM_CURRENT_FLAG=1
	AND ENTRY_CATEGORY_TYPE_CD IN ('HVS', 'LVS', 'OIC')
)

SELECT DISTINCT
airbill.AWB_NBR,
clr.ACTIVITY_DATA_DESC,
emp.EMPLOYEE_NBR,
clr.ACTIVITY_TMSTP,
shp_fct.CUSTOMS_VALUE_AMT,
int_code_dim.INTERCEPT_CD,
shp_core_clr_fct.ENTRY_CATEGORY_TYPE_CD

FROM clr INNER JOIN emp ON (clr.CREATED_EMPL_WNBR = emp.PM_PRIMARYKEY) INNER JOIN
emp_info ON (emp.EMPLOYEE_NBR = emp_info.emp_nbr) INNER JOIN
shp_fct ON (clr.AIRBILL_WNBR = shp_fct.AIRBILL_WNBR)INNER JOIN
airbill ON (clr.AIRBILL_WNBR = airbill.PM_PRIMARYKEY) INNER JOIN
int_fct ON (clr.AIRBILL_WNBR = int_fct.AIRBILL_WNBR) INNER JOIN
int_code_dim ON (int_fct.INTERCEPT_CODE_WNBR=int_code_dim.PM_PRIMARYKEY) INNER JOIN
shp_core_clr_fct ON (clr.AIRBILL_WNBR = shp_core_clr_fct.AIRBILL_WNBR);