SELECT DISTINCT
-- SELECT TOP 100
AL3.tracking_id_nbr as AWB_NBR, 
AL5.CREATION_EMP_NBR as EMPLOYEE_NBR,
AL3.transaction_nbr as CANADIAN_ENTRY_NBR,
AL6.TARIFF_CODE as TARIFF_ANNEX_CD,
AL6.COMMODITY_SEQUENCE_NBR as COMMODITY_LINE_NBR,
AL6.COMMODITY_DESC, 
AL7.HARMONIZED_TARIFF_NBR, 
AL6.TOTAL_UNIT_CAD_AMT as TOTAL_VALUE_DUTY_AMT, 
AL3.oga_shipment_flg, 
AL1.DATE_DT, 
AL2.DATE_DT as REL_DATE,
AL3.rod_flg, 
AL5.TOTAL_DUE as cad_value_amt,
AL6.GST_AMT as SALES_TAX_AMT,
-- AL6.HST_AMT, 
AL6.PST_AMT as PROVINCIAL_SALES_TAX_AMT,
-- AL6.QST_AMT, 
AL6.SIMA_CHARGES as SPCL_IMPT_MEAS_ACT_TAX_AMT,
-- AL6.SURTAX_AMT, 
AL6.CUSTOMS_DUTY as DUTY_AMT,
AL6.OIC_DOCUMENT as ORDER_IN_COUNCIL_DOC_NBR,
AL5.OFFICE_NBR as CLEARANCE_PORT_CD,
AL5.CASUAL,
AL8.NME as COMPANY_NM,
-- AL8.ADDRESS1, 
AL8.CITY as CITY_NM,
AL8.STATE as STATE_CD,
AL6.COM as MANUF_ORIGIN_COUNTRY_CD, --This one is different from CUSMA_40
AL8.POSTAL as POSTAL_CD,
AL8.DUTY_BILL_TO_ACCT_NBR, 
AL4.COUNTRY_CD as COUNTRY_CD,
AL3.csa_flg,
AL6.TARIFF_TREATMENT_CD as TARIFF_TREATMENT_CD,
AL5.DUTY_VALUE
-- AL3.duty_bill_to_cd

-- AL6.COM

FROM MISA_PROD_VIEW_DB.TIME_DIM AL1, MISA_PROD_VIEW_DB.TIME_DIM AL2, MISA_PROD_VIEW_DB.CLASSIFY_SHIPMENT_FACT AL3, MISA_PROD_VIEW_DB.COUNTRY_DIM AL4, MISA_PROD_VIEW_DB.CLASSIFY_DT_SHPMT_HDR_FACT AL5, MISA_PROD_VIEW_DB.CLASSIFY_DT_COMMODITY_RECAP AL6, MISA_PROD_VIEW_DB.COMMODITY_DIM AL7, MISA_PROD_VIEW_DB.CLASSIFY_DT_SHIPMENT_PARTY AL8 WHERE (AL1.TIME_WNBR=AL3.input_dt_wnbr AND AL4.PM_PRIMARYKEY=AL3.export_country_wnbr AND AL5.LOCAL_SHIPMENT_OID_NBR=AL6.LOCAL_SHIPMENT_OID_NBR AND AL6.COMMODITY_WNBR=AL7.PM_PRIMARYKEY AND AL5.RELEASE_DATE_WNBR=AL2.TIME_WNBR AND AL3.local_shipment_oid_nbr=AL5.LOCAL_SHIPMENT_OID_NBR AND AL8.LOCAL_SHIPMENT_OID_NBR=AL5.LOCAL_SHIPMENT_OID_NBR)  AND ((AL3.pm_current_flag=1 AND (NOT (AL6.COMMODITY_DESC LIKE '%alcohol%' OR AL6.COMMODITY_DESC LIKE '%books%' OR AL6.COMMODITY_DESC LIKE '%cigar%' OR AL6.COMMODITY_DESC LIKE '%gift%' OR AL6.COMMODITY_DESC LIKE '%newsprint%' OR AL6.COMMODITY_DESC LIKE '%paper%' OR AL6.COMMODITY_DESC LIKE '%smokes%' OR AL6.COMMODITY_DESC LIKE '%tonic%' OR AL6.COMMODITY_DESC LIKE '%wine%')) AND AL5.PM_CURRENT_FLAG=1 AND AL6.PM_CURRENT_FLAG=1 AND AL8.CUSTOMER_TYPE='I' 

AND AL1.DATE_DT BETWEEN DATE {starting} AND DATE {ending} AND AL6.COM NOT  IN ('AD', 'AT', 'BE', 'BG', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'MC', 'MT', 'NL', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK', 'SM') AND AL5.CASUAL='Y' AND AL6.TARIFF_TREATMENT_CD='31'))
