SELECT 
AL1.tracking_id_nbr as Awb_Nbr,
COUNT (AL2.COMMODITY_SEQUENCE_NBR) as N_of_Lines,
AL10.process_control_data_desc as Value_Flg,
AL4.COUNTRY_CD as COO,
AL9.COUNTRY_CD as COE,
AL5.NME as Importer_Nm,
AL5.DUTY_BILL_TO_ACCT_NBR as Duty_Bill_To_Acct_Nbr,
AL6.LOCATION_CD as Clr_Loc,
AL7.DATE_DT as Entry_Dt,
AL8.DATE_DT as Release_Dt,
AL1.rod_flg as Rod_Flg,
AL3.LAST_MODIFIED_EID as Employee,
AL3.DUTY_VALUE as Customs_Value_In_CAD
 
FROM MISA_PROD_VIEW_DB.CLASSIFY_SHIPMENT_FACT AL1, MISA_PROD_VIEW_DB.CLASSIFY_DT_COMMODITY_RECAP AL2, MISA_PROD_VIEW_DB.CLASSIFY_DT_SHPMT_HDR_FACT AL3, MISA_PROD_VIEW_DB.COUNTRY_DIM AL4, MISA_PROD_VIEW_DB.CLASSIFY_DT_SHIPMENT_PARTY AL5, MISA_PROD_VIEW_DB.LOCATION_DIM AL6, MISA_PROD_VIEW_DB.TIME_DIM AL7, MISA_PROD_VIEW_DB.TIME_DIM AL8, MISA_PROD_VIEW_DB.COUNTRY_DIM AL9, MISA_PROD_VIEW_DB.CLASSIFY_SHPMT_PRCS_CTRL AL10 WHERE (AL2.LOCAL_SHIPMENT_OID_NBR=AL3.LOCAL_SHIPMENT_OID_NBR AND AL3.LOCAL_SHIPMENT_OID_NBR=AL1.local_shipment_oid_nbr AND AL5.LOCAL_SHIPMENT_OID_NBR=AL3.LOCAL_SHIPMENT_OID_NBR AND AL1.final_import_clrnc_loc_wnbr=AL6.PM_PRIMARYKEY AND AL1.input_dt_wnbr=AL7.TIME_WNBR AND AL3.RELEASE_DATE_WNBR=AL8.TIME_WNBR AND AL1.local_shipment_oid_nbr=AL10.local_shipment_oid_nbr AND AL1.export_country_wnbr=AL9.PM_PRIMARYKEY AND AL1.origin_loc_cntry_wnbr=AL4.PM_PRIMARYKEY)  AND ((AL3.PM_CURRENT_FLAG=1 AND AL1.pm_current_flag=1 AND AL2.PM_CURRENT_FLAG=1 AND AL8.DATE_DT BETWEEN DATE 

--change date
{starting} AND DATE {ending}

AND AL4.COUNTRY_CD IN ('AD', 'AT', 'BE', 'BG', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'MC', 'MT', 'NL', 'PL', 'PT', 'RO', 'SE', 'SK', 'SL', 'SM') AND AL9.COUNTRY_CD IN ('AD', 'AT', 'BE', 'BG', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'MC', 'MT', 'NL', 'PL', 'PT', 'RO', 'SE', 'SK', 'SL', 'SM') AND AL10.process_control_type_desc='ENTRYS' AND AL3.STATUS IN ('ACCEPTED BY CUSTOMS', 'COMPLETED', 'STAGED FOR CONSOLIDATION') AND AL5.CUSTOMER_TYPE='I')) GROUP BY AL1.tracking_id_nbr, AL10.process_control_data_desc, AL4.COUNTRY_CD, AL9.COUNTRY_CD, AL5.NME, AL5.DUTY_BILL_TO_ACCT_NBR, AL6.LOCATION_CD, AL7.DATE_DT, AL8.DATE_DT, AL1.rod_flg, AL3.LAST_MODIFIED_EID, AL3.DUTY_VALUE
;