SELECT 
AL1.tracking_id_nbr as Awb_Nbr,
COUNT (AL2.COMMODITY_SEQUENCE_NBR) as N_of_Lines,
AL5.DUTY_BILL_TO_ACCT_NBR as Duty_Bill_To_Acct_Nbr,
AL4.COUNTRY_CD as COO,
AL8.COUNTRY_CD as COE,
AL5.NME as Importer_Nm,
AL6.DATE_DT as Entry_Dt,
AL7.DATE_DT as Release_Dt,
AL9.process_control_data_desc as Value_Flg,
AL1.rod_flg as Rod_Flg,
AL3.LAST_MODIFIED_EID as Employee,
AL3.DUTY_VALUE as Customs_Value_In_CAD

FROM MISA_PROD_VIEW_DB.CLASSIFY_SHIPMENT_FACT AL1, MISA_PROD_VIEW_DB.CLASSIFY_DT_COMMODITY_RECAP AL2, MISA_PROD_VIEW_DB.CLASSIFY_DT_SHPMT_HDR_FACT AL3, MISA_PROD_VIEW_DB.COUNTRY_DIM AL4, MISA_PROD_VIEW_DB.CLASSIFY_DT_SHIPMENT_PARTY AL5, MISA_PROD_VIEW_DB.TIME_DIM AL6, MISA_PROD_VIEW_DB.TIME_DIM AL7, MISA_PROD_VIEW_DB.COUNTRY_DIM AL8, MISA_PROD_VIEW_DB.CLASSIFY_SHPMT_PRCS_CTRL AL9 WHERE (AL2.LOCAL_SHIPMENT_OID_NBR=AL3.LOCAL_SHIPMENT_OID_NBR AND AL3.LOCAL_SHIPMENT_OID_NBR=AL1.local_shipment_oid_nbr AND AL5.LOCAL_SHIPMENT_OID_NBR=AL3.LOCAL_SHIPMENT_OID_NBR AND AL1.input_dt_wnbr=AL6.TIME_WNBR AND AL3.RELEASE_DATE_WNBR=AL7.TIME_WNBR AND AL1.local_shipment_oid_nbr=AL9.local_shipment_oid_nbr AND AL8.PM_PRIMARYKEY=AL1.export_country_wnbr AND AL4.PM_PRIMARYKEY=AL1.origin_loc_cntry_wnbr)  AND ((AL1.pm_current_flag=1 AND AL3.PM_CURRENT_FLAG=1 AND AL2.PM_CURRENT_FLAG=1 AND AL7.DATE_DT BETWEEN DATE 

--change date
{starting} AND DATE {ending}

AND (NOT AL2.TARIFF_TREATMENT_CD='31') AND (NOT AL3.CASUAL='Y') AND AL4.COUNTRY_CD='GB' AND AL8.COUNTRY_CD='GB' AND AL9.process_control_type_desc='ENTRYS' AND AL3.STATUS IN ('ACCEPTED BY CUSTOMS', 'COMPLETED', 'STAGED FOR CONSOLIDATION') AND AL3.DUTY_VALUE>150 AND AL5.CUSTOMER_TYPE='I')) GROUP BY AL1.tracking_id_nbr, AL5.DUTY_BILL_TO_ACCT_NBR, AL4.COUNTRY_CD, AL8.COUNTRY_CD, AL5.NME, AL6.DATE_DT, AL7.DATE_DT, AL9.process_control_data_desc, AL1.rod_flg, AL3.LAST_MODIFIED_EID, AL3.DUTY_VALUE
;